name: ci
on: push
jobs:
  test-frontend:
    name: test-frontend
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint
      # - run: yarn test

  test-backend:
    name: test-backend
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: bestsell
          POSTGRES_USER: root
          POSTGRES_PASSWORD: test
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - run: poetry --version
      - run: poetry config experimental.new-installer false
      - run: poetry install
      - run: make lint
      - name: pytest
        run: make test
        env:
          DB_HOST: localhost
          DB_NAME: bestsell
          DB_USER: root
          DB_PASSWORD: test
